name: Azure Static Web Apps CI/CD

on:
  workflow_run:
    workflows:
      - Quality Matrix
    types:
      - completed
    branches:
      - main
  pull_request:
jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: install, build
        run: |
          yarn --frozen-lockfile
          yarn ci:quality:core
          yarn ci:storybook

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PLANT_07A086E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          skip_app_build: true
          skip_api_build: true
          app_location: '/storybook-static' # App source code path
  build_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build PR
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: install, build
        run: |
          yarn --frozen-lockfile
          yarn ci:quality:core
          yarn ci:storybook
