name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: install, build
        run: |
          yarn
          yarn build
          yarn build-storybook

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PLANT_07A086E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/storybook-static" # App source code path
  build_pr:
    if: github.event_name != 'push' || (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    name: Build PR
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: install, build, test
        run: |
          yarn
          yarn build
          yarn build-storybook
          yarn test
